### ISSUE TITLE
Not running under Windows

### ISSUE THREAD

**Issue by Saiv46** [mattrobenolt/node_pickle#2]
```
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/env ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
    at onErrorNT (internal/child_process.js:442:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
    at onErrorNT (internal/child_process.js:442:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by irfancnk** [comment]
I think this repo is not maintained anymore

**Comment by agds23** [comment]
> ```
> events.js:173
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn /usr/bin/env ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:19)
>     at onErrorNT (internal/child_process.js:442:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:9)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
>     at onErrorNT (internal/child_process.js:442:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:9)
> ```

Hi! @Saiv46  and @irfancnk any news or you migrated to another solution? Thanks

**Comment by Saiv46** [comment]
@agds23 There's no other solution yet. I just wrote my own implementation which does exactly like this package, but this is messy so I don't publish it anywhere.

**Comment by mattrobenolt** [comment]
Yeah, yall, this is really bad software I wrote 9 years ago as a very quick and terrible hack. It's extremely limited in what it can even do since it can only handle the most basic primitive types. If nothing exists, someone should just write something that decodes these primitive types from the pickle bytes directly, the schema isn't that complex. Also, another pro tip, just don't use pickle. Use literally any other encoding format other than pickle, and you'll be doing great.
